openapi: 3.0.0
info:
  title: APIs de usuários finalizada. Em desenvolvimento APIs do chat!
  version: 1.0.0
  description: Documentação das APIs do chat
servers:
  - url: http://localhost:5000
paths:
  /api/users/register:
    post:
      summary: Registra um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Usuário registrado com sucesso
        '400':
          description: Erro ao registrar o usuário
  /api/users/login:
    post:
      summary: Realiza o login de um usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login realizado com sucesso
        '400':
          description: Erro ao realizar o login
  /api/users/find/{userId}:
    get:
      summary: Retorna um usuário pelo ID
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Usuário encontrado
        '404':
          description: Usuário não encontrado
  /api/users:
    get:
      summary: Retorna todos os usuários
      responses:
        '200':
          description: Lista de usuários
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
